const wordDatabase = [
    { id: "w1", eng: "Ubiquitous", nl: "Alomtegenwoordig", context: "Smartphones have become ubiquitous in modern society.", category: "Advanced" },
    { id: "w2", eng: "Pertinent", nl: "Relevant / Ter zake doend", context: "Please keep your questions pertinent to the topic.", category: "Business" },
    { id: "w3", eng: "Alleviate", nl: "Verlichten / Verzachten", context: "This medicine will alleviate the pain.", category: "Advanced" },
    { id: "w4", eng: "Ambiguous", nl: "Dubbelzinnig / Onduidelijk", context: "His answer was too ambiguous to be helpful.", category: "Advanced" },
    { id: "w5", eng: "Mitigate", nl: "Verzachten / Beperken", context: "We need to mitigate the risks before proceeding.", category: "Business" },
    { id: "w6", eng: "Synergy", nl: "Synergie / Samenwerking", context: "The synergy between our teams is excellent.", category: "Business" },
    { id: "w7", eng: "Feasible", nl: "Haalbaar / Uitvoerbaar", context: "Is it feasible to finish this by Friday?", category: "Business" },
    { id: "w8", eng: "Resilient", nl: "Veerkrachtig", context: "The company proved to be highly resilient during the crisis.", category: "Advanced" },
    { id: "w9", eng: "Lucrative", nl: "Winstgevend", context: "They signed a highly lucrative contract.", category: "Business" },
    { id: "w10", eng: "Eloquent", nl: "Welsprekend", context: "She gave an eloquent speech at the conference.", category: "Advanced" },
    { id: "w11", eng: "Pragmatic", nl: "Pragmatisch / Praktisch", context: "We need a pragmatic approach to this problem.", category: "Business" },
    { id: "w12", eng: "Diligence", nl: "Toewijding / Zorgvuldigheid", context: "He was promoted for his diligence and hard work.", category: "Business" },
    { id: "w13", eng: "Tedious", nl: "Saai / Langdradig", context: "Data entry can be a very tedious task.", category: "Advanced" },
    { id: "w14", eng: "Leverage", nl: "Benutten / Als hefboom gebruiken", context: "We must leverage our resources effectively.", category: "Business" },
    { id: "w15", eng: "Vulnerable", nl: "Kwetsbaar", context: "The system is vulnerable to cyber attacks.", category: "Advanced" },
    { id: "w16", eng: "Consensus", nl: "Overeenstemming", context: "We eventually reached a consensus on the new policy.", category: "Business" },
    { id: "w17", eng: "Scrutinize", nl: "Nauwkeurig onderzoeken", context: "We must scrutinize the contract before signing.", category: "Business" },
    { id: "w18", eng: "Inevitable", nl: "Onvermijdelijk", context: "Change in the tech industry is inevitable.", category: "Advanced" },
    { id: "w19", eng: "Tangible", nl: "Tastbaar / Concreet", context: "We need tangible results by the end of the quarter.", category: "Business" },
    { id: "w20", eng: "Subtle", nl: "Subtiel", context: "There is a subtle difference between the two concepts.", category: "Advanced" },
    { id: "w21", eng: "Obsolete", nl: "Verouderd / Achterhaald", context: "Floppy disks are completely obsolete today.", category: "Advanced" },
    { id: "w22", eng: "Paradigm", nl: "Paradigma / Wereldbeeld", context: "There was a paradigm shift in how we approach software.", category: "Business" },
    { id: "w23", eng: "Empower", nl: "In staat stellen / Machtigen", context: "We want to empower our employees to make decisions.", category: "Business" },
    { id: "w24", eng: "Impeccable", nl: "Onberispelijk / Vlekkeloos", context: "Her professional record is impeccable.", category: "Advanced" },
    { id: "w25", eng: "Acumen", nl: "Scherpzinnigheid", context: "He has excellent business acumen.", category: "Business" },
    { id: "w26", eng: "Tenacious", nl: "Vasthoudend / Volhardend", context: "She was tenacious in pursuing her career goals.", category: "Advanced" },
    { id: "w27", eng: "Meticulous", nl: "Uitermate zorgvuldig", context: "The project requires meticulous planning.", category: "Advanced" },
    { id: "w28", eng: "Viable", nl: "Levensvatbaar / Realistisch", context: "We need a commercially viable solution.", category: "Business" },
    { id: "w29", eng: "Candid", nl: "Openerhartig / Eerlijk", context: "Let me be candid about my feedback.", category: "Advanced" },
    { id: "w30", eng: "Exacerbate", nl: "Verergeren", context: "His comments only served to exacerbate the situation.", category: "Advanced" },
    { id: "w31", eng: "Pivotal", nl: "Cruciaal / Doorslaggevend", context: "She played a pivotal role in the negotiations.", category: "Business" },
    { id: "w32", eng: "Discrepancy", nl: "Tegenstrijdigheid / Verschil", context: "There is a discrepancy in the financial reports.", category: "Business" },
    { id: "w33", eng: "Clandestine", nl: "Geheim / Heimelijk", context: "They held a clandestine meeting.", category: "Advanced" },
    { id: "w34", eng: "Flourish", nl: "Floreren / Bloeien", context: "The business began to flourish under new management.", category: "Advanced" },
    { id: "w35", eng: "Onerous", nl: "Zwaar / Lastig", context: "Reviewing all those documents is an onerous task.", category: "Business" },
    { id: "w36", eng: "Proponent", nl: "Voorstander", context: "He is a strong proponent of renewable energy.", category: "Advanced" },
    { id: "w37", eng: "Retaliate", nl: "Terugslaan / Wraak nemen", context: "The competitor will likely retaliate with lower prices.", category: "Business" },
    { id: "w38", eng: "Sustain", nl: "Handhaven / Volhouden", context: "We cannot sustain this level of growth indefinitely.", category: "Business" },
    { id: "w39", eng: "Unprecedented", nl: "Ongekend", context: "The crisis was completely unprecedented.", category: "Advanced" },
    { id: "w40", eng: "Versatile", nl: "Veelzijdig", context: "This tool is extremely versatile for many jobs.", category: "Advanced" },
    { id: "w41", eng: "Complacent", nl: "Zelfvoldaan", context: "We cannot afford to become complacent with our success.", category: "Business" },
    { id: "w42", eng: "Deteriorate", nl: "Verslechteren", context: "The market conditions continue to deteriorate.", category: "Advanced" },
    { id: "w43", eng: "Epitome", nl: "Hét perfecte voorbeeld", context: "She is the epitome of professionalism.", category: "Advanced" },
    { id: "w44", eng: "Fluctuate", nl: "Schommelen", context: "Currency rates fluctuate daily.", category: "Business" },
    { id: "w45", eng: "Plausible", nl: "Aannemelijk / Geloofwaardig", context: "That seems like a plausible explanation.", category: "Advanced" },
    { id: "w46", eng: "Reiterate", nl: "Herhalen", context: "Let me reiterate the main points of our strategy.", category: "Business" },
    { id: "w47", eng: "Rigorous", nl: "Streng / Grondig", context: "The product went through rigorous testing.", category: "Advanced" },
    { id: "w48", eng: "Stagnant", nl: "Stilstaand", context: "The economy has been stagnant for three years.", category: "Business" },
    { id: "w49", eng: "Underlying", nl: "Onderliggend", context: "We must identify the underlying cause of this issue.", category: "Advanced" },
    { id: "w50", eng: "Vindicate", nl: "Zuiveren (van blaam) / Rechtvaardigen", context: "The new evidence will vindicate him.", category: "Advanced" },
    { id: "w51", eng: "Acknowledge", nl: "Erkennen / Bevestigen", context: "Please acknowledge receipt of this email.", category: "Business" },
    { id: "w52", eng: "Benchmark", nl: "Referentiekader", context: "Their success became the benchmark for the industry.", category: "Business" },
    { id: "w53", eng: "Catalyst", nl: "Katalysator", context: "The new law was a catalyst for economic recovery.", category: "Business" },
    { id: "w54", eng: "Deficit", nl: "Tekort", context: "The company aims to reduce its budget deficit.", category: "Business" },
    { id: "w55", eng: "Endeavor", nl: "Onderneming / Poging", context: "Good luck with your new business endeavor.", category: "Business" },
    { id: "w56", eng: "Fringe benefit", nl: "Secundaire arbeidsvoorwaarde", context: "A company car is a great fringe benefit.", category: "Business" },
    { id: "w57", eng: "Grievance", nl: "Grief / Klacht", context: "Employees can file a grievance with HR.", category: "Business" },
    { id: "w58", eng: "Implement", nl: "Invoeren / Uitvoeren", context: "We plan to implement the new software next month.", category: "Business" },
    { id: "w59", eng: "Jurisdiction", nl: "Rechtsgebied / Bevoegdheid", context: "That matter falls outside our jurisdiction.", category: "Business" },
    { id: "w60", eng: "Liability", nl: "Aansprakelijkheid", context: "The company accepts no liability for delays.", category: "Business" },
    { id: "w61", eng: "Mandatory", nl: "Verplicht", context: "Attendance at the meeting is mandatory.", category: "Business" },
    { id: "w62", eng: "Niche", nl: "Specifiek marktsegment", context: "They found a profitable niche in the tech market.", category: "Business" },
    { id: "w63", eng: "Overhead", nl: "Vaste lasten", context: "We need to figure out ways to lower our overhead.", category: "Business" },
    { id: "w64", eng: "Procurement", nl: "Inkoop / Verwerving", context: "He works as a manager in public procurement.", category: "Business" },
    { id: "w65", eng: "Quota", nl: "Quotum / Aandeel", context: "The sales team met their monthly quota.", category: "Business" },
    { id: "w66", eng: "Remuneration", nl: "Beloning / Vergoeding", context: "They offered fair remuneration for the extra work.", category: "Business" },
    { id: "w67", eng: "Stakeholder", nl: "Belanghebbende", context: "We must update all external stakeholders immediately.", category: "Business" },
    { id: "w68", eng: "Turnover", nl: "Omzet / Verloop", context: "Staff turnover has been surprisingly low this year.", category: "Business" },
    { id: "w69", eng: "Vendor", nl: "Verkoper / Leverancier", context: "We are looking for a new software vendor.", category: "Business" },
    { id: "w70", eng: "Wholesale", nl: "Groothandel", context: "We buy our materials wholesale to save costs.", category: "Business" },
    { id: "w71", eng: "Yield", nl: "Opbrengen", context: "The investment is expected to yield high returns.", category: "Business" },
    { id: "w72", eng: "Zenith", nl: "Hoogtepunt", context: "His career reached its zenith in the early 2000s.", category: "Advanced" },
    { id: "w73", eng: "Acquisition", nl: "Aankoop / Overname", context: "Our recent acquisition of a smaller firm was successful.", category: "Business" },
    { id: "w74", eng: "Bottleneck", nl: "Knelpunt", context: "Shipping delays are a bottleneck in our supply chain.", category: "Business" },
    { id: "w75", eng: "Commodity", nl: "Handelswaar / Grondstof", context: "Gold is a highly valuable global commodity.", category: "Business" },
    { id: "w76", eng: "Deduction", nl: "Aftrek / Afleiding", context: "You can count that as a tax deduction.", category: "Business" },
    { id: "w77", eng: "Equity", nl: "Vermogen / Aandeel / Eerlijkheid", context: "He owns 20% equity in the startup.", category: "Business" },
    { id: "w78", eng: "Franchise", nl: "Concessie / Filiaal", context: "They decided to open a fast-food franchise.", category: "Business" },
    { id: "w79", eng: "Gross", nl: "Bruto", context: "What is the team's total gross income?", category: "Business" },
    { id: "w80", eng: "Hedge", nl: "Indekken (tegen risico's)", context: "We must hedge against currency fluctuations.", category: "Business" },
    { id: "w81", eng: "Incentive", nl: "Prikkel / Stimulans", context: "Bonus pay is a great financial incentive.", category: "Business" },
    { id: "w82", eng: "Jargon", nl: "Vaktaal", context: "Avoid using too much technical jargon.", category: "Business" },
    { id: "w83", eng: "Kickback", nl: "Smeergeld", context: "The executive was accused of taking a kickback.", category: "Business" },
    { id: "w84", eng: "Liquidity", nl: "Liquiditeit", context: "The business is suffering from poor liquidity.", category: "Business" },
    { id: "w85", eng: "Monopoly", nl: "Monopolie", context: "The company holds a virtual monopoly in the market.", category: "Business" },
    { id: "w86", eng: "Negligence", nl: "Nalatigheid", context: "The accident was caused by sheer negligence.", category: "Business" },
    { id: "w87", eng: "Outsource", nl: "Uitbesteden", context: "We outsource our customer support to a call center.", category: "Business" },
    { id: "w88", eng: "Portfolio", nl: "Portefeuille", context: "Our company has a diversified product portfolio.", category: "Business" },
    { id: "w89", eng: "Quarter", nl: "Kwartaal", context: "Profits fell heavily in the first quarter.", category: "Business" },
    { id: "w90", eng: "Revenue", nl: "Opbrengst / Omzet", context: "Advertising generates much of our daily revenue.", category: "Business" },
    { id: "w91", eng: "Subsidy", nl: "Subsidie", context: "The agriculture sector receives a massive government subsidy.", category: "Business" },
    { id: "w92", eng: "Tariff", nl: "Douanerecht / Tarief", context: "They imposed a high tariff on imported steel.", category: "Business" },
    { id: "w93", eng: "Unanimous", nl: "Unaniem", context: "The board reached a unanimous decision.", category: "Business" },
    { id: "w94", eng: "Venture", nl: "Risicovolle onderneming", context: "They entered a dangerous new joint venture.", category: "Business" },
    { id: "w95", eng: "Waiver", nl: "Afstandsverklaring", context: "You must sign a waiver before going parachuting.", category: "Business" },
    { id: "w96", eng: "Adept", nl: "Bekwaam / Handig", context: "She is highly adept at solving technical issues.", category: "Advanced" },
    { id: "w97", eng: "Bypass", nl: "Omzeilen", context: "We found a way to bypass the slow procedure.", category: "Business" },
    { id: "w98", eng: "Curb", nl: "Intomen / Beperken", context: "Measures must be taken to curb inflation.", category: "Advanced" },
    { id: "w99", eng: "Disclose", nl: "Onthullen / Openbaar maken", context: "You must disclose all relevant financial information.", category: "Business" },
    { id: "w100", eng: "Evade", nl: "Ontwijken", context: "He tried to evade paying his corporate taxes.", category: "Advanced" }
];
